load_module /usr/lib/nginx/modules/ngx_stream_module.so;

worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 16384;
}

stream {
    log_format tcp '$remote_addr [$time_local] $protocol $status '
                   '$bytes_sent $bytes_received $session_time upstream=$upstream_addr';
    access_log /var/log/nginx/access.log tcp;

    upstream poker_lobby {
        least_conn;
        server poker-lobby:7000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 6000;
        proxy_connect_timeout 3s;
        proxy_timeout 75s;
        proxy_pass poker_lobby;
    }
}
