global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: poker
    static_configs:
      - targets:
          - poker-lobby:9100
          - poker-game-a:9100
          - poker-game-b:9100
