#ifndef PUBLIC_HPP
#define PUBLIC_HPP

enum EnMsgType{
    LOGIN_MSG = 1,
    LOGIN_MSG_ACK,
    REG_MSG,
    REG_MSG_ACK,
    POINT_CHAT_MSG,
    POINT_CHAT_MSG_ACK,
    ADD_FRIEND_MSG,
    ADD_FRIEND_MSG_ACK,
    REMOVE_FRIEND_MSG,
    REMOVE_FRIEND_MSG_ACK
};


#endif